name: gee_downloader
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - numpy
  - pandas
  - rasterio
  - scipy
  - earthengine-api
  - google-cloud-bigquery
  - plumbum
  - gdal
  - pendulum
  - pip
  - pip:
      # works for regular pip packages
      - db_dtypes # this package needs to be installed using pip install